package input

// Dead keys on the French (fr-FR AZERTY) layout.
var (
	frTrema = &pasteChar{HID: hidBracketLeft, Modifier: modShiftLeft} // ¨ (BracketLeft shift)
	frHat   = &pasteChar{HID: hidBracketLeft}                         // ^ (BracketLeft base)
)

// frFRPasteChars is the French (fr-FR AZERTY) paste map.
// Ported from JetKVM web app's fr_FR layout.
//
// Note: French AZERTY swaps several keys vs QWERTY:
//   A↔Q, W↔Z, M is at the Semicolon position, digits require Shift.
var frFRPasteChars = pasteLayout{
	'A': {HID: hidQ, Modifier: modShiftLeft},
	'Ä': {HID: hidQ, Modifier: modShiftLeft, Accent: frTrema},
	'Â': {HID: hidQ, Modifier: modShiftLeft, Accent: frHat},
	'B': {HID: hidB, Modifier: modShiftLeft},
	'C': {HID: hidC, Modifier: modShiftLeft},
	'D': {HID: hidD, Modifier: modShiftLeft},
	'E': {HID: hidE, Modifier: modShiftLeft},
	'Ë': {HID: hidE, Modifier: modShiftLeft, Accent: frTrema},
	'Ê': {HID: hidE, Modifier: modShiftLeft, Accent: frHat},
	'F': {HID: hidF, Modifier: modShiftLeft},
	'G': {HID: hidG, Modifier: modShiftLeft},
	'H': {HID: hidH, Modifier: modShiftLeft},
	'I': {HID: hidI, Modifier: modShiftLeft},
	'Ï': {HID: hidI, Modifier: modShiftLeft, Accent: frTrema},
	'Î': {HID: hidI, Modifier: modShiftLeft, Accent: frHat},
	'J': {HID: hidJ, Modifier: modShiftLeft},
	'K': {HID: hidK, Modifier: modShiftLeft},
	'L': {HID: hidL, Modifier: modShiftLeft},
	'M': {HID: hidSemicolon, Modifier: modShiftLeft},
	'N': {HID: hidN, Modifier: modShiftLeft},
	'O': {HID: hidO, Modifier: modShiftLeft},
	'Ö': {HID: hidO, Modifier: modShiftLeft, Accent: frTrema},
	'Ô': {HID: hidO, Modifier: modShiftLeft, Accent: frHat},
	'P': {HID: hidP, Modifier: modShiftLeft},
	'Q': {HID: hidA, Modifier: modShiftLeft},
	'R': {HID: hidR, Modifier: modShiftLeft},
	'S': {HID: hidS, Modifier: modShiftLeft},
	'T': {HID: hidT, Modifier: modShiftLeft},
	'U': {HID: hidU, Modifier: modShiftLeft},
	'Ü': {HID: hidU, Modifier: modShiftLeft, Accent: frTrema},
	'Û': {HID: hidU, Modifier: modShiftLeft, Accent: frHat},
	'V': {HID: hidV, Modifier: modShiftLeft},
	'W': {HID: hidZ, Modifier: modShiftLeft},
	'X': {HID: hidX, Modifier: modShiftLeft},
	'Y': {HID: hidY, Modifier: modShiftLeft},
	'Z': {HID: hidW, Modifier: modShiftLeft},

	'a': {HID: hidQ},
	'ä': {HID: hidQ, Accent: frTrema},
	'â': {HID: hidQ, Accent: frHat},
	'b': {HID: hidB},
	'c': {HID: hidC},
	'd': {HID: hidD},
	'e': {HID: hidE},
	'ë': {HID: hidE, Accent: frTrema},
	'ê': {HID: hidE, Accent: frHat},
	'€': {HID: hidE, Modifier: modAltRight},
	'f': {HID: hidF},
	'g': {HID: hidG},
	'h': {HID: hidH},
	'i': {HID: hidI},
	'ï': {HID: hidI, Accent: frTrema},
	'î': {HID: hidI, Accent: frHat},
	'j': {HID: hidJ},
	'k': {HID: hidK},
	'l': {HID: hidL},
	'm': {HID: hidSemicolon},
	'n': {HID: hidN},
	'o': {HID: hidO},
	'ö': {HID: hidO, Accent: frTrema},
	'ô': {HID: hidO, Accent: frHat},
	'p': {HID: hidP},
	'q': {HID: hidA},
	'r': {HID: hidR},
	's': {HID: hidS},
	't': {HID: hidT},
	'u': {HID: hidU},
	'ü': {HID: hidU, Accent: frTrema},
	'û': {HID: hidU, Accent: frHat},
	'v': {HID: hidV},
	'w': {HID: hidZ},
	'x': {HID: hidX},
	'y': {HID: hidY},
	'z': {HID: hidW},

	'²': {HID: hidBackquote},

	// Digits require Shift on AZERTY
	'&':  {HID: hidDigit1},
	'1':  {HID: hidDigit1, Modifier: modShiftLeft},
	'é':  {HID: hidDigit2},
	'2':  {HID: hidDigit2, Modifier: modShiftLeft},
	'~':  {HID: hidDigit2, Modifier: modAltRight},
	'"':  {HID: hidDigit3},
	'3':  {HID: hidDigit3, Modifier: modShiftLeft},
	'#':  {HID: hidDigit3, Modifier: modAltRight},
	'\'': {HID: hidDigit4},
	'4':  {HID: hidDigit4, Modifier: modShiftLeft},
	'{':  {HID: hidDigit4, Modifier: modAltRight},
	'(':  {HID: hidDigit5},
	'5':  {HID: hidDigit5, Modifier: modShiftLeft},
	'[':  {HID: hidDigit5, Modifier: modAltRight},
	'-':  {HID: hidDigit6},
	'6':  {HID: hidDigit6, Modifier: modShiftLeft},
	'|':  {HID: hidDigit6, Modifier: modAltRight},
	'è':  {HID: hidDigit7},
	'7':  {HID: hidDigit7, Modifier: modShiftLeft},
	'`':  {HID: hidDigit7, Modifier: modAltRight},
	'_':  {HID: hidDigit8},
	'8':  {HID: hidDigit8, Modifier: modShiftLeft},
	'\\': {HID: hidDigit8, Modifier: modAltRight},
	'ç':  {HID: hidDigit9},
	'9':  {HID: hidDigit9, Modifier: modShiftLeft},
	'^':  {HID: hidDigit9, Modifier: modAltRight},
	'à':  {HID: hidDigit0},
	'0':  {HID: hidDigit0, Modifier: modShiftLeft},
	'@':  {HID: hidDigit0, Modifier: modAltRight},

	')':  {HID: hidMinus},
	'°':  {HID: hidMinus, Modifier: modShiftLeft},
	']':  {HID: hidMinus, Modifier: modAltRight},
	'=':  {HID: hidEqual},
	'+':  {HID: hidEqual, Modifier: modShiftLeft},
	'}':  {HID: hidEqual, Modifier: modAltRight},
	'$':  {HID: hidBracketRight},
	'£':  {HID: hidBracketRight, Modifier: modShiftLeft},
	'¤':  {HID: hidBracketRight, Modifier: modAltRight},
	'ù':  {HID: hidQuote},
	'%':  {HID: hidQuote, Modifier: modShiftLeft},
	'*':  {HID: hidBackslash},
	'µ':  {HID: hidBackslash, Modifier: modShiftLeft},
	',':  {HID: hidM},
	'?':  {HID: hidM, Modifier: modShiftLeft},
	';':  {HID: hidComma},
	'.':  {HID: hidComma, Modifier: modShiftLeft},
	':':  {HID: hidPeriod},
	'/':  {HID: hidPeriod, Modifier: modShiftLeft},
	'!':  {HID: hidSlash},
	'§':  {HID: hidSlash, Modifier: modShiftLeft},
	'<':  {HID: hidIntlBackslash},
	'>':  {HID: hidIntlBackslash, Modifier: modShiftLeft},

	' ':  {HID: hidSpace},
	'\n': {HID: hidEnter},
	'\r': {HID: hidEnter},
	'\t': {HID: hidTab},
}
