package input

// itITPasteChars is the Italian (it-IT) paste map.
// Ported from JetKVM web app's it_IT layout.
var itITPasteChars = pasteLayout{
	'A': {HID: hidA, Modifier: modShiftLeft},
	'B': {HID: hidB, Modifier: modShiftLeft},
	'C': {HID: hidC, Modifier: modShiftLeft},
	'D': {HID: hidD, Modifier: modShiftLeft},
	'E': {HID: hidE, Modifier: modShiftLeft},
	'F': {HID: hidF, Modifier: modShiftLeft},
	'G': {HID: hidG, Modifier: modShiftLeft},
	'H': {HID: hidH, Modifier: modShiftLeft},
	'I': {HID: hidI, Modifier: modShiftLeft},
	'J': {HID: hidJ, Modifier: modShiftLeft},
	'K': {HID: hidK, Modifier: modShiftLeft},
	'L': {HID: hidL, Modifier: modShiftLeft},
	'M': {HID: hidM, Modifier: modShiftLeft},
	'N': {HID: hidN, Modifier: modShiftLeft},
	'O': {HID: hidO, Modifier: modShiftLeft},
	'P': {HID: hidP, Modifier: modShiftLeft},
	'Q': {HID: hidQ, Modifier: modShiftLeft},
	'R': {HID: hidR, Modifier: modShiftLeft},
	'S': {HID: hidS, Modifier: modShiftLeft},
	'T': {HID: hidT, Modifier: modShiftLeft},
	'U': {HID: hidU, Modifier: modShiftLeft},
	'V': {HID: hidV, Modifier: modShiftLeft},
	'W': {HID: hidW, Modifier: modShiftLeft},
	'X': {HID: hidX, Modifier: modShiftLeft},
	'Y': {HID: hidY, Modifier: modShiftLeft},
	'Z': {HID: hidZ, Modifier: modShiftLeft},

	'a': {HID: hidA}, 'b': {HID: hidB}, 'c': {HID: hidC}, 'd': {HID: hidD},
	'e': {HID: hidE}, 'f': {HID: hidF}, 'g': {HID: hidG}, 'h': {HID: hidH},
	'i': {HID: hidI}, 'j': {HID: hidJ}, 'k': {HID: hidK}, 'l': {HID: hidL},
	'm': {HID: hidM}, 'n': {HID: hidN}, 'o': {HID: hidO}, 'p': {HID: hidP},
	'q': {HID: hidQ}, 'r': {HID: hidR}, 's': {HID: hidS}, 't': {HID: hidT},
	'u': {HID: hidU}, 'v': {HID: hidV}, 'w': {HID: hidW}, 'x': {HID: hidX},
	'y': {HID: hidY}, 'z': {HID: hidZ},
	'€': {HID: hidE, Modifier: modAltRight},

	'\\': {HID: hidBackquote},
	'|':  {HID: hidBackquote, Modifier: modShiftLeft},

	'1': {HID: hidDigit1},
	'!': {HID: hidDigit1, Modifier: modShiftLeft},
	'2': {HID: hidDigit2},
	'"': {HID: hidDigit2, Modifier: modShiftLeft},
	'3': {HID: hidDigit3},
	'£': {HID: hidDigit3, Modifier: modShiftLeft},
	'4': {HID: hidDigit4},
	'$': {HID: hidDigit4, Modifier: modShiftLeft},
	'5': {HID: hidDigit5},
	'%': {HID: hidDigit5, Modifier: modShiftLeft},
	'6': {HID: hidDigit6},
	'&': {HID: hidDigit6, Modifier: modShiftLeft},
	'7': {HID: hidDigit7},
	'/': {HID: hidDigit7, Modifier: modShiftLeft},
	'8': {HID: hidDigit8},
	'(': {HID: hidDigit8, Modifier: modShiftLeft},
	'9': {HID: hidDigit9},
	')': {HID: hidDigit9, Modifier: modShiftLeft},
	'0': {HID: hidDigit0},
	'=': {HID: hidDigit0, Modifier: modShiftLeft},

	'\'': {HID: hidMinus},
	'?':  {HID: hidMinus, Modifier: modShiftLeft},
	'ì':  {HID: hidEqual},
	'^':  {HID: hidEqual, Modifier: modShiftLeft},
	'è':  {HID: hidBracketLeft},
	'é':  {HID: hidBracketLeft, Modifier: modShiftLeft},
	'[':  {HID: hidBracketLeft, Modifier: modAltRight},
	'{':  {HID: hidBracketLeft, Modifier: modShiftLeft | modAltRight},
	'+':  {HID: hidBracketRight},
	'*':  {HID: hidBracketRight, Modifier: modShiftLeft},
	']':  {HID: hidBracketRight, Modifier: modAltRight},
	'}':  {HID: hidBracketRight, Modifier: modShiftLeft | modAltRight},
	'ò':  {HID: hidSemicolon},
	'ç':  {HID: hidSemicolon, Modifier: modShiftLeft},
	'@':  {HID: hidSemicolon, Modifier: modAltRight},
	'à':  {HID: hidQuote},
	'°':  {HID: hidQuote, Modifier: modShiftLeft},
	'#':  {HID: hidQuote, Modifier: modAltRight},
	'ù':  {HID: hidBackslash},
	'§':  {HID: hidBackslash, Modifier: modShiftLeft},
	',':  {HID: hidComma},
	';':  {HID: hidComma, Modifier: modShiftLeft},
	'.':  {HID: hidPeriod},
	':':  {HID: hidPeriod, Modifier: modShiftLeft},
	'-':  {HID: hidSlash},
	'_':  {HID: hidSlash, Modifier: modShiftLeft},
	'<':  {HID: hidIntlBackslash},
	'>':  {HID: hidIntlBackslash, Modifier: modShiftLeft},

	' ':  {HID: hidSpace},
	'\n': {HID: hidEnter},
	'\r': {HID: hidEnter},
	'\t': {HID: hidTab},
}
