package input

// Dead keys on the German (de-DE) layout.
var (
	deAcute = &pasteChar{HID: hidEqual}                     // ´ (Equal base)
	deHat   = &pasteChar{HID: hidBackquote}                 // ^ (Backquote base)
	deGrave = &pasteChar{HID: hidEqual, Modifier: modShiftLeft} // ` (Equal shift)
)

// deDEPasteChars is the German (de-DE) paste map.
// Ported from JetKVM web app's de_DE layout.
//
// Note: the German layout swaps Y and Z compared to QWERTY.
var deDEPasteChars = pasteLayout{
	'a': {HID: hidA},
	'á': {HID: hidA, Accent: deAcute},
	'â': {HID: hidA, Accent: deHat},
	'à': {HID: hidA, Accent: deGrave},
	'A': {HID: hidA, Modifier: modShiftLeft},
	'Á': {HID: hidA, Modifier: modShiftLeft, Accent: deAcute},
	'Â': {HID: hidA, Modifier: modShiftLeft, Accent: deHat},
	'À': {HID: hidA, Modifier: modShiftLeft, Accent: deGrave},
	'b': {HID: hidB},
	'B': {HID: hidB, Modifier: modShiftLeft},
	'c': {HID: hidC},
	'C': {HID: hidC, Modifier: modShiftLeft},
	'd': {HID: hidD},
	'D': {HID: hidD, Modifier: modShiftLeft},
	'e': {HID: hidE},
	'é': {HID: hidE, Accent: deAcute},
	'ê': {HID: hidE, Accent: deHat},
	'è': {HID: hidE, Accent: deGrave},
	'€': {HID: hidE, Modifier: modAltRight},
	'E': {HID: hidE, Modifier: modShiftLeft},
	'É': {HID: hidE, Modifier: modShiftLeft, Accent: deAcute},
	'Ê': {HID: hidE, Modifier: modShiftLeft, Accent: deHat},
	'È': {HID: hidE, Modifier: modShiftLeft, Accent: deGrave},
	'f': {HID: hidF},
	'F': {HID: hidF, Modifier: modShiftLeft},
	'g': {HID: hidG},
	'G': {HID: hidG, Modifier: modShiftLeft},
	'ẞ': {HID: hidG, Modifier: modAltRight},
	'h': {HID: hidH},
	'H': {HID: hidH, Modifier: modShiftLeft},
	'i': {HID: hidI},
	'í': {HID: hidI, Accent: deAcute},
	'î': {HID: hidI, Accent: deHat},
	'ì': {HID: hidI, Accent: deGrave},
	'I': {HID: hidI, Modifier: modShiftLeft},
	'Í': {HID: hidI, Modifier: modShiftLeft, Accent: deAcute},
	'Î': {HID: hidI, Modifier: modShiftLeft, Accent: deHat},
	'Ì': {HID: hidI, Modifier: modShiftLeft, Accent: deGrave},
	'j': {HID: hidJ},
	'J': {HID: hidJ, Modifier: modShiftLeft},
	'k': {HID: hidK},
	'K': {HID: hidK, Modifier: modShiftLeft},
	'l': {HID: hidL},
	'L': {HID: hidL, Modifier: modShiftLeft},
	'm': {HID: hidM},
	'M': {HID: hidM, Modifier: modShiftLeft},
	'µ': {HID: hidM, Modifier: modAltRight},
	'n': {HID: hidN},
	'N': {HID: hidN, Modifier: modShiftLeft},
	'o': {HID: hidO},
	'ó': {HID: hidO, Accent: deAcute},
	'ô': {HID: hidO, Accent: deHat},
	'ò': {HID: hidO, Accent: deGrave},
	'O': {HID: hidO, Modifier: modShiftLeft},
	'Ó': {HID: hidO, Modifier: modShiftLeft, Accent: deAcute},
	'Ô': {HID: hidO, Modifier: modShiftLeft, Accent: deHat},
	'Ò': {HID: hidO, Modifier: modShiftLeft, Accent: deGrave},
	'p': {HID: hidP},
	'P': {HID: hidP, Modifier: modShiftLeft},
	'q': {HID: hidQ},
	'Q': {HID: hidQ, Modifier: modShiftLeft},
	'@': {HID: hidQ, Modifier: modAltRight},
	'r': {HID: hidR},
	'R': {HID: hidR, Modifier: modShiftLeft},
	's': {HID: hidS},
	'S': {HID: hidS, Modifier: modShiftLeft},
	't': {HID: hidT},
	'T': {HID: hidT, Modifier: modShiftLeft},
	'u': {HID: hidU},
	'ú': {HID: hidU, Accent: deAcute},
	'û': {HID: hidU, Accent: deHat},
	'ù': {HID: hidU, Accent: deGrave},
	'U': {HID: hidU, Modifier: modShiftLeft},
	'Ú': {HID: hidU, Modifier: modShiftLeft, Accent: deAcute},
	'Û': {HID: hidU, Modifier: modShiftLeft, Accent: deHat},
	'Ù': {HID: hidU, Modifier: modShiftLeft, Accent: deGrave},
	'v': {HID: hidV},
	'V': {HID: hidV, Modifier: modShiftLeft},
	'«': {HID: hidV, Modifier: modAltRight},
	'w': {HID: hidW},
	'W': {HID: hidW, Modifier: modShiftLeft},
	'x': {HID: hidX},
	'X': {HID: hidX, Modifier: modShiftLeft},
	'»': {HID: hidX, Modifier: modAltRight},
	// Y and Z are swapped on the German layout
	'y': {HID: hidZ},
	'Y': {HID: hidZ, Modifier: modShiftLeft},
	'z': {HID: hidY},
	'Z': {HID: hidY, Modifier: modShiftLeft},

	'°': {HID: hidBackquote, Modifier: modShiftLeft},
	'^': {HID: hidBackquote, DeadKey: true},
	'|': {HID: hidBackquote, Modifier: modAltRight},

	'1':  {HID: hidDigit1},
	'!':  {HID: hidDigit1, Modifier: modShiftLeft},
	'2':  {HID: hidDigit2},
	'"':  {HID: hidDigit2, Modifier: modShiftLeft},
	'²':  {HID: hidDigit2, Modifier: modAltRight},
	'3':  {HID: hidDigit3},
	'§':  {HID: hidDigit3, Modifier: modShiftLeft},
	'³':  {HID: hidDigit3, Modifier: modAltRight},
	'4':  {HID: hidDigit4},
	'$':  {HID: hidDigit4, Modifier: modShiftLeft},
	'5':  {HID: hidDigit5},
	'%':  {HID: hidDigit5, Modifier: modShiftLeft},
	'6':  {HID: hidDigit6},
	'&':  {HID: hidDigit6, Modifier: modShiftLeft},
	'7':  {HID: hidDigit7},
	'/':  {HID: hidDigit7, Modifier: modShiftLeft},
	'{':  {HID: hidDigit7, Modifier: modAltRight},
	'8':  {HID: hidDigit8},
	'(':  {HID: hidDigit8, Modifier: modShiftLeft},
	'[':  {HID: hidDigit8, Modifier: modAltRight},
	'9':  {HID: hidDigit9},
	')':  {HID: hidDigit9, Modifier: modShiftLeft},
	']':  {HID: hidDigit9, Modifier: modAltRight},
	'0':  {HID: hidDigit0},
	'=':  {HID: hidDigit0, Modifier: modShiftLeft},
	'}':  {HID: hidDigit0, Modifier: modAltRight},
	'ß':  {HID: hidMinus},
	'?':  {HID: hidMinus, Modifier: modShiftLeft},
	'\\': {HID: hidMinus, Modifier: modAltRight},
	'´':  {HID: hidEqual, DeadKey: true},
	'`':  {HID: hidEqual, Modifier: modShiftLeft, DeadKey: true},
	'ü':  {HID: hidBracketLeft},
	'Ü':  {HID: hidBracketLeft, Modifier: modShiftLeft},
	'+':  {HID: hidBracketRight},
	'*':  {HID: hidBracketRight, Modifier: modShiftLeft},
	'~':  {HID: hidBracketRight, Modifier: modAltRight},
	'ö':  {HID: hidSemicolon},
	'Ö':  {HID: hidSemicolon, Modifier: modShiftLeft},
	'ä':  {HID: hidQuote},
	'Ä':  {HID: hidQuote, Modifier: modShiftLeft},
	'#':  {HID: hidBackslash},
	'\'': {HID: hidBackslash, Modifier: modShiftLeft},
	',':  {HID: hidComma},
	';':  {HID: hidComma, Modifier: modShiftLeft},
	'.':  {HID: hidPeriod},
	':':  {HID: hidPeriod, Modifier: modShiftLeft},
	'·':  {HID: hidPeriod, Modifier: modAltRight},
	'-':  {HID: hidSlash},
	'_':  {HID: hidSlash, Modifier: modShiftLeft},
	'<':  {HID: hidIntlBackslash},
	'>':  {HID: hidIntlBackslash, Modifier: modShiftLeft},

	' ':  {HID: hidSpace},
	'\n': {HID: hidEnter},
	'\r': {HID: hidEnter},
	'\t': {HID: hidTab},
}
