package input

// Dead keys on the Spanish (es-ES) layout.
var (
	esTrema = &pasteChar{HID: hidQuote, Modifier: modShiftLeft}        // ¨ (Quote shift)
	esAcute = &pasteChar{HID: hidQuote}                                // ´ (Quote base)
	esHat   = &pasteChar{HID: hidBracketRight, Modifier: modShiftLeft} // ^ (BracketRight shift)
	esGrave = &pasteChar{HID: hidBracketRight}                         // ` (BracketRight base)
	esTilde = &pasteChar{HID: hidDigit4, Modifier: modAltRight}        // ~ (AltGr+4 on ES)
)

// esESPasteChars is the Spanish (es-ES) paste map.
// Ported from JetKVM web app's es_ES layout.
var esESPasteChars = pasteLayout{
	'A': {HID: hidA, Modifier: modShiftLeft},
	'Ä': {HID: hidA, Modifier: modShiftLeft, Accent: esTrema},
	'Á': {HID: hidA, Modifier: modShiftLeft, Accent: esAcute},
	'Â': {HID: hidA, Modifier: modShiftLeft, Accent: esHat},
	'À': {HID: hidA, Modifier: modShiftLeft, Accent: esGrave},
	'Ã': {HID: hidA, Modifier: modShiftLeft, Accent: esTilde},
	'B': {HID: hidB, Modifier: modShiftLeft},
	'C': {HID: hidC, Modifier: modShiftLeft},
	'D': {HID: hidD, Modifier: modShiftLeft},
	'E': {HID: hidE, Modifier: modShiftLeft},
	'Ë': {HID: hidE, Modifier: modShiftLeft, Accent: esTrema},
	'É': {HID: hidE, Modifier: modShiftLeft, Accent: esAcute},
	'Ê': {HID: hidE, Modifier: modShiftLeft, Accent: esHat},
	'È': {HID: hidE, Modifier: modShiftLeft, Accent: esGrave},
	'F': {HID: hidF, Modifier: modShiftLeft},
	'G': {HID: hidG, Modifier: modShiftLeft},
	'H': {HID: hidH, Modifier: modShiftLeft},
	'I': {HID: hidI, Modifier: modShiftLeft},
	'Ï': {HID: hidI, Modifier: modShiftLeft, Accent: esTrema},
	'Í': {HID: hidI, Modifier: modShiftLeft, Accent: esAcute},
	'Î': {HID: hidI, Modifier: modShiftLeft, Accent: esHat},
	'Ì': {HID: hidI, Modifier: modShiftLeft, Accent: esGrave},
	'J': {HID: hidJ, Modifier: modShiftLeft},
	'K': {HID: hidK, Modifier: modShiftLeft},
	'L': {HID: hidL, Modifier: modShiftLeft},
	'M': {HID: hidM, Modifier: modShiftLeft},
	'N': {HID: hidN, Modifier: modShiftLeft},
	'O': {HID: hidO, Modifier: modShiftLeft},
	'Ö': {HID: hidO, Modifier: modShiftLeft, Accent: esTrema},
	'Ó': {HID: hidO, Modifier: modShiftLeft, Accent: esAcute},
	'Ô': {HID: hidO, Modifier: modShiftLeft, Accent: esHat},
	'Ò': {HID: hidO, Modifier: modShiftLeft, Accent: esGrave},
	'Õ': {HID: hidO, Modifier: modShiftLeft, Accent: esTilde},
	'P': {HID: hidP, Modifier: modShiftLeft},
	'Q': {HID: hidQ, Modifier: modShiftLeft},
	'R': {HID: hidR, Modifier: modShiftLeft},
	'S': {HID: hidS, Modifier: modShiftLeft},
	'T': {HID: hidT, Modifier: modShiftLeft},
	'U': {HID: hidU, Modifier: modShiftLeft},
	'Ü': {HID: hidU, Modifier: modShiftLeft, Accent: esTrema},
	'Ú': {HID: hidU, Modifier: modShiftLeft, Accent: esAcute},
	'Û': {HID: hidU, Modifier: modShiftLeft, Accent: esHat},
	'Ù': {HID: hidU, Modifier: modShiftLeft, Accent: esGrave},
	'V': {HID: hidV, Modifier: modShiftLeft},
	'W': {HID: hidW, Modifier: modShiftLeft},
	'X': {HID: hidX, Modifier: modShiftLeft},
	'Y': {HID: hidY, Modifier: modShiftLeft},
	'Z': {HID: hidZ, Modifier: modShiftLeft},

	'a': {HID: hidA},
	'ä': {HID: hidA, Accent: esTrema},
	'á': {HID: hidA, Accent: esAcute},
	'â': {HID: hidA, Accent: esHat},
	'à': {HID: hidA, Accent: esGrave},
	'ã': {HID: hidA, Accent: esTilde},
	'b': {HID: hidB},
	'c': {HID: hidC},
	'd': {HID: hidD},
	'e': {HID: hidE},
	'ë': {HID: hidE, Accent: esTrema},
	'é': {HID: hidE, Accent: esAcute},
	'ê': {HID: hidE, Accent: esHat},
	'è': {HID: hidE, Accent: esGrave},
	'€': {HID: hidE, Modifier: modAltRight},
	'f': {HID: hidF},
	'g': {HID: hidG},
	'h': {HID: hidH},
	'i': {HID: hidI},
	'ï': {HID: hidI, Accent: esTrema},
	'í': {HID: hidI, Accent: esAcute},
	'î': {HID: hidI, Accent: esHat},
	'ì': {HID: hidI, Accent: esGrave},
	'j': {HID: hidJ},
	'k': {HID: hidK},
	'l': {HID: hidL},
	'm': {HID: hidM},
	'n': {HID: hidN},
	'o': {HID: hidO},
	'ö': {HID: hidO, Accent: esTrema},
	'ó': {HID: hidO, Accent: esAcute},
	'ô': {HID: hidO, Accent: esHat},
	'ò': {HID: hidO, Accent: esGrave},
	'õ': {HID: hidO, Accent: esTilde},
	'p': {HID: hidP},
	'q': {HID: hidQ},
	'r': {HID: hidR},
	's': {HID: hidS},
	't': {HID: hidT},
	'u': {HID: hidU},
	'ü': {HID: hidU, Accent: esTrema},
	'ú': {HID: hidU, Accent: esAcute},
	'û': {HID: hidU, Accent: esHat},
	'ù': {HID: hidU, Accent: esGrave},
	'v': {HID: hidV},
	'w': {HID: hidW},
	'x': {HID: hidX},
	'y': {HID: hidY},
	'z': {HID: hidZ},

	'º':  {HID: hidBackquote},
	'ª':  {HID: hidBackquote, Modifier: modShiftLeft},
	'\\': {HID: hidBackquote, Modifier: modAltRight},

	'1':  {HID: hidDigit1},
	'!':  {HID: hidDigit1, Modifier: modShiftLeft},
	'|':  {HID: hidDigit1, Modifier: modAltRight},
	'2':  {HID: hidDigit2},
	'"':  {HID: hidDigit2, Modifier: modShiftLeft},
	'@':  {HID: hidDigit2, Modifier: modAltRight},
	'3':  {HID: hidDigit3},
	'·':  {HID: hidDigit3, Modifier: modShiftLeft},
	'#':  {HID: hidDigit3, Modifier: modAltRight},
	'4':  {HID: hidDigit4},
	'$':  {HID: hidDigit4, Modifier: modShiftLeft},
	'5':  {HID: hidDigit5},
	'%':  {HID: hidDigit5, Modifier: modShiftLeft},
	'6':  {HID: hidDigit6},
	'&':  {HID: hidDigit6, Modifier: modShiftLeft},
	'¬':  {HID: hidDigit6, Modifier: modAltRight},
	'7':  {HID: hidDigit7},
	'/':  {HID: hidDigit7, Modifier: modShiftLeft},
	'8':  {HID: hidDigit8},
	'(':  {HID: hidDigit8, Modifier: modShiftLeft},
	'9':  {HID: hidDigit9},
	')':  {HID: hidDigit9, Modifier: modShiftLeft},
	'0':  {HID: hidDigit0},
	'=':  {HID: hidDigit0, Modifier: modShiftLeft},

	'\'': {HID: hidMinus},
	'?':  {HID: hidMinus, Modifier: modShiftLeft},
	'¡':  {HID: hidEqual, DeadKey: true},
	'¿':  {HID: hidEqual, Modifier: modShiftLeft},
	'[':  {HID: hidBracketLeft, Modifier: modAltRight},
	'+':  {HID: hidBracketRight},
	'*':  {HID: hidBracketRight, Modifier: modShiftLeft},
	']':  {HID: hidBracketRight, Modifier: modAltRight},
	'ñ':  {HID: hidSemicolon},
	'Ñ':  {HID: hidSemicolon, Modifier: modShiftLeft},
	'{':  {HID: hidQuote, Modifier: modAltRight},
	'ç':  {HID: hidBackslash},
	'Ç':  {HID: hidBackslash, Modifier: modShiftLeft},
	'}':  {HID: hidBackslash, Modifier: modAltRight},
	',':  {HID: hidComma},
	';':  {HID: hidComma, Modifier: modShiftLeft},
	'.':  {HID: hidPeriod},
	':':  {HID: hidPeriod, Modifier: modShiftLeft},
	'-':  {HID: hidSlash},
	'_':  {HID: hidSlash, Modifier: modShiftLeft},
	'<':  {HID: hidIntlBackslash},
	'>':  {HID: hidIntlBackslash, Modifier: modShiftLeft},

	' ':  {HID: hidSpace},
	'\n': {HID: hidEnter},
	'\r': {HID: hidEnter},
	'\t': {HID: hidTab},
}
