// Code generated by "enumer -type=launcherMode,settingsActionGroup,mediaView -linecomment -json -text -output app_enums.go"; DO NOT EDIT.

package app

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _launcherModeName = "browsepassword"

var _launcherModeIndex = [...]uint8{0, 6, 14}

const _launcherModeLowerName = "browsepassword"

func (i launcherMode) String() string {
	if i >= launcherMode(len(_launcherModeIndex)-1) {
		return fmt.Sprintf("launcherMode(%d)", i)
	}
	return _launcherModeName[_launcherModeIndex[i]:_launcherModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _launcherModeNoOp() {
	var x [1]struct{}
	_ = x[launcherModeBrowse-(0)]
	_ = x[launcherModePassword-(1)]
}

var _launcherModeValues = []launcherMode{launcherModeBrowse, launcherModePassword}

var _launcherModeNameToValueMap = map[string]launcherMode{
	_launcherModeName[0:6]:       launcherModeBrowse,
	_launcherModeLowerName[0:6]:  launcherModeBrowse,
	_launcherModeName[6:14]:      launcherModePassword,
	_launcherModeLowerName[6:14]: launcherModePassword,
}

var _launcherModeNames = []string{
	_launcherModeName[0:6],
	_launcherModeName[6:14],
}

// launcherModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func launcherModeString(s string) (launcherMode, error) {
	if val, ok := _launcherModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _launcherModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to launcherMode values", s)
}

// launcherModeValues returns all values of the enum
func launcherModeValues() []launcherMode {
	return _launcherModeValues
}

// launcherModeStrings returns a slice of all String values of the enum
func launcherModeStrings() []string {
	strs := make([]string, len(_launcherModeNames))
	copy(strs, _launcherModeNames)
	return strs
}

// IsAlauncherMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i launcherMode) IsAlauncherMode() bool {
	for _, v := range _launcherModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for launcherMode
func (i launcherMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for launcherMode
func (i *launcherMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("launcherMode should be a string, got %s", data)
	}

	var err error
	*i, err = launcherModeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for launcherMode
func (i launcherMode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for launcherMode
func (i *launcherMode) UnmarshalText(text []byte) error {
	var err error
	*i, err = launcherModeString(string(text))
	return err
}

const _settingsActionGroupName = "keyboard_layoutvideo_qualityvideo_codecvideo_edidatx_poweractive_extensiondc_powerserial_settingsserial_commandtls_modedisplay_rotationbacklightvideo_sleepusb_emulationusb_devicesauto_updateupdate_statusdeveloper_modedev_channelloopback_onlyssh_keynetwork_savemacros_savejigglerlocal_authmqtt_savemqtt_testupdate_installfactory_resetnetwork_refreshnetwork_renew_dhcpusb_network_save"

var _settingsActionGroupIndex = [...]uint16{0, 15, 28, 39, 49, 58, 74, 82, 97, 111, 119, 135, 144, 155, 168, 179, 190, 203, 217, 228, 241, 248, 260, 271, 278, 288, 297, 306, 320, 333, 348, 366, 382}

const _settingsActionGroupLowerName = "keyboard_layoutvideo_qualityvideo_codecvideo_edidatx_poweractive_extensiondc_powerserial_settingsserial_commandtls_modedisplay_rotationbacklightvideo_sleepusb_emulationusb_devicesauto_updateupdate_statusdeveloper_modedev_channelloopback_onlyssh_keynetwork_savemacros_savejigglerlocal_authmqtt_savemqtt_testupdate_installfactory_resetnetwork_refreshnetwork_renew_dhcpusb_network_save"

func (i settingsActionGroup) String() string {
	if i >= settingsActionGroup(len(_settingsActionGroupIndex)-1) {
		return fmt.Sprintf("settingsActionGroup(%d)", i)
	}
	return _settingsActionGroupName[_settingsActionGroupIndex[i]:_settingsActionGroupIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _settingsActionGroupNoOp() {
	var x [64]struct{}
	_ = x[settingsGroupKeyboardLayout-(0)]
	_ = x[settingsGroupVideoQuality-(1)]
	_ = x[settingsGroupVideoCodec-(2)]
	_ = x[settingsGroupVideoEDID-(3)]
	_ = x[settingsGroupATXPower-(4)]
	_ = x[settingsGroupActiveExtension-(5)]
	_ = x[settingsGroupDCPower-(6)]
	_ = x[settingsGroupSerialSettings-(7)]
	_ = x[settingsGroupSerialCommand-(8)]
	_ = x[settingsGroupTLSMode-(9)]
	_ = x[settingsGroupDisplayRotate-(10)]
	_ = x[settingsGroupBacklight-(11)]
	_ = x[settingsGroupVideoSleep-(12)]
	_ = x[settingsGroupUSBEmulation-(13)]
	_ = x[settingsGroupUSBDevices-(14)]
	_ = x[settingsGroupAutoUpdate-(15)]
	_ = x[settingsGroupUpdateStatus-(16)]
	_ = x[settingsGroupDeveloperMode-(17)]
	_ = x[settingsGroupDevChannel-(18)]
	_ = x[settingsGroupLoopbackOnly-(19)]
	_ = x[settingsGroupSSHKey-(20)]
	_ = x[settingsGroupNetworkSave-(21)]
	_ = x[settingsGroupMacrosSave-(22)]
	_ = x[settingsGroupJiggler-(23)]
	_ = x[settingsGroupLocalAuth-(24)]
	_ = x[settingsGroupMQTTSave-(25)]
	_ = x[settingsGroupMQTTTest-(26)]
	_ = x[settingsGroupUpdateInstall-(27)]
	_ = x[settingsGroupFactoryReset-(28)]
	_ = x[settingsGroupNetworkRefresh-(29)]
	_ = x[settingsGroupNetworkRenew-(30)]
	_ = x[settingsGroupUSBNetworkSave-(31)]
}

var _settingsActionGroupValues = []settingsActionGroup{settingsGroupKeyboardLayout, settingsGroupVideoQuality, settingsGroupVideoCodec, settingsGroupVideoEDID, settingsGroupATXPower, settingsGroupActiveExtension, settingsGroupDCPower, settingsGroupSerialSettings, settingsGroupSerialCommand, settingsGroupTLSMode, settingsGroupDisplayRotate, settingsGroupBacklight, settingsGroupVideoSleep, settingsGroupUSBEmulation, settingsGroupUSBDevices, settingsGroupAutoUpdate, settingsGroupUpdateStatus, settingsGroupDeveloperMode, settingsGroupDevChannel, settingsGroupLoopbackOnly, settingsGroupSSHKey, settingsGroupNetworkSave, settingsGroupMacrosSave, settingsGroupJiggler, settingsGroupLocalAuth, settingsGroupMQTTSave, settingsGroupMQTTTest, settingsGroupUpdateInstall, settingsGroupFactoryReset, settingsGroupNetworkRefresh, settingsGroupNetworkRenew, settingsGroupUSBNetworkSave}

var _settingsActionGroupNameToValueMap = map[string]settingsActionGroup{
	_settingsActionGroupName[0:15]:         settingsGroupKeyboardLayout,
	_settingsActionGroupLowerName[0:15]:    settingsGroupKeyboardLayout,
	_settingsActionGroupName[15:28]:        settingsGroupVideoQuality,
	_settingsActionGroupLowerName[15:28]:   settingsGroupVideoQuality,
	_settingsActionGroupName[28:39]:        settingsGroupVideoCodec,
	_settingsActionGroupLowerName[28:39]:   settingsGroupVideoCodec,
	_settingsActionGroupName[39:49]:        settingsGroupVideoEDID,
	_settingsActionGroupLowerName[39:49]:   settingsGroupVideoEDID,
	_settingsActionGroupName[49:58]:        settingsGroupATXPower,
	_settingsActionGroupLowerName[49:58]:   settingsGroupATXPower,
	_settingsActionGroupName[58:74]:        settingsGroupActiveExtension,
	_settingsActionGroupLowerName[58:74]:   settingsGroupActiveExtension,
	_settingsActionGroupName[74:82]:        settingsGroupDCPower,
	_settingsActionGroupLowerName[74:82]:   settingsGroupDCPower,
	_settingsActionGroupName[82:97]:        settingsGroupSerialSettings,
	_settingsActionGroupLowerName[82:97]:   settingsGroupSerialSettings,
	_settingsActionGroupName[97:111]:       settingsGroupSerialCommand,
	_settingsActionGroupLowerName[97:111]:  settingsGroupSerialCommand,
	_settingsActionGroupName[111:119]:      settingsGroupTLSMode,
	_settingsActionGroupLowerName[111:119]: settingsGroupTLSMode,
	_settingsActionGroupName[119:135]:      settingsGroupDisplayRotate,
	_settingsActionGroupLowerName[119:135]: settingsGroupDisplayRotate,
	_settingsActionGroupName[135:144]:      settingsGroupBacklight,
	_settingsActionGroupLowerName[135:144]: settingsGroupBacklight,
	_settingsActionGroupName[144:155]:      settingsGroupVideoSleep,
	_settingsActionGroupLowerName[144:155]: settingsGroupVideoSleep,
	_settingsActionGroupName[155:168]:      settingsGroupUSBEmulation,
	_settingsActionGroupLowerName[155:168]: settingsGroupUSBEmulation,
	_settingsActionGroupName[168:179]:      settingsGroupUSBDevices,
	_settingsActionGroupLowerName[168:179]: settingsGroupUSBDevices,
	_settingsActionGroupName[179:190]:      settingsGroupAutoUpdate,
	_settingsActionGroupLowerName[179:190]: settingsGroupAutoUpdate,
	_settingsActionGroupName[190:203]:      settingsGroupUpdateStatus,
	_settingsActionGroupLowerName[190:203]: settingsGroupUpdateStatus,
	_settingsActionGroupName[203:217]:      settingsGroupDeveloperMode,
	_settingsActionGroupLowerName[203:217]: settingsGroupDeveloperMode,
	_settingsActionGroupName[217:228]:      settingsGroupDevChannel,
	_settingsActionGroupLowerName[217:228]: settingsGroupDevChannel,
	_settingsActionGroupName[228:241]:      settingsGroupLoopbackOnly,
	_settingsActionGroupLowerName[228:241]: settingsGroupLoopbackOnly,
	_settingsActionGroupName[241:248]:      settingsGroupSSHKey,
	_settingsActionGroupLowerName[241:248]: settingsGroupSSHKey,
	_settingsActionGroupName[248:260]:      settingsGroupNetworkSave,
	_settingsActionGroupLowerName[248:260]: settingsGroupNetworkSave,
	_settingsActionGroupName[260:271]:      settingsGroupMacrosSave,
	_settingsActionGroupLowerName[260:271]: settingsGroupMacrosSave,
	_settingsActionGroupName[271:278]:      settingsGroupJiggler,
	_settingsActionGroupLowerName[271:278]: settingsGroupJiggler,
	_settingsActionGroupName[278:288]:      settingsGroupLocalAuth,
	_settingsActionGroupLowerName[278:288]: settingsGroupLocalAuth,
	_settingsActionGroupName[288:297]:      settingsGroupMQTTSave,
	_settingsActionGroupLowerName[288:297]: settingsGroupMQTTSave,
	_settingsActionGroupName[297:306]:      settingsGroupMQTTTest,
	_settingsActionGroupLowerName[297:306]: settingsGroupMQTTTest,
	_settingsActionGroupName[306:320]:      settingsGroupUpdateInstall,
	_settingsActionGroupLowerName[306:320]: settingsGroupUpdateInstall,
	_settingsActionGroupName[320:333]:      settingsGroupFactoryReset,
	_settingsActionGroupLowerName[320:333]: settingsGroupFactoryReset,
	_settingsActionGroupName[333:348]:      settingsGroupNetworkRefresh,
	_settingsActionGroupLowerName[333:348]: settingsGroupNetworkRefresh,
	_settingsActionGroupName[348:366]:      settingsGroupNetworkRenew,
	_settingsActionGroupLowerName[348:366]: settingsGroupNetworkRenew,
	_settingsActionGroupName[366:382]:      settingsGroupUSBNetworkSave,
	_settingsActionGroupLowerName[366:382]: settingsGroupUSBNetworkSave,
}

var _settingsActionGroupNames = []string{
	_settingsActionGroupName[0:15],
	_settingsActionGroupName[15:28],
	_settingsActionGroupName[28:39],
	_settingsActionGroupName[39:49],
	_settingsActionGroupName[49:58],
	_settingsActionGroupName[58:74],
	_settingsActionGroupName[74:82],
	_settingsActionGroupName[82:97],
	_settingsActionGroupName[97:111],
	_settingsActionGroupName[111:119],
	_settingsActionGroupName[119:135],
	_settingsActionGroupName[135:144],
	_settingsActionGroupName[144:155],
	_settingsActionGroupName[155:168],
	_settingsActionGroupName[168:179],
	_settingsActionGroupName[179:190],
	_settingsActionGroupName[190:203],
	_settingsActionGroupName[203:217],
	_settingsActionGroupName[217:228],
	_settingsActionGroupName[228:241],
	_settingsActionGroupName[241:248],
	_settingsActionGroupName[248:260],
	_settingsActionGroupName[260:271],
	_settingsActionGroupName[271:278],
	_settingsActionGroupName[278:288],
	_settingsActionGroupName[288:297],
	_settingsActionGroupName[297:306],
	_settingsActionGroupName[306:320],
	_settingsActionGroupName[320:333],
	_settingsActionGroupName[333:348],
	_settingsActionGroupName[348:366],
	_settingsActionGroupName[366:382],
}

// settingsActionGroupString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func settingsActionGroupString(s string) (settingsActionGroup, error) {
	if val, ok := _settingsActionGroupNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _settingsActionGroupNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to settingsActionGroup values", s)
}

// settingsActionGroupValues returns all values of the enum
func settingsActionGroupValues() []settingsActionGroup {
	return _settingsActionGroupValues
}

// settingsActionGroupStrings returns a slice of all String values of the enum
func settingsActionGroupStrings() []string {
	strs := make([]string, len(_settingsActionGroupNames))
	copy(strs, _settingsActionGroupNames)
	return strs
}

// IsAsettingsActionGroup returns "true" if the value is listed in the enum definition. "false" otherwise
func (i settingsActionGroup) IsAsettingsActionGroup() bool {
	for _, v := range _settingsActionGroupValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for settingsActionGroup
func (i settingsActionGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for settingsActionGroup
func (i *settingsActionGroup) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("settingsActionGroup should be a string, got %s", data)
	}

	var err error
	*i, err = settingsActionGroupString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for settingsActionGroup
func (i settingsActionGroup) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for settingsActionGroup
func (i *settingsActionGroup) UnmarshalText(text []byte) error {
	var err error
	*i, err = settingsActionGroupString(string(text))
	return err
}

const _mediaViewName = "homeurlstorageupload"

var _mediaViewIndex = [...]uint8{0, 4, 7, 14, 20}

const _mediaViewLowerName = "homeurlstorageupload"

func (i mediaView) String() string {
	if i >= mediaView(len(_mediaViewIndex)-1) {
		return fmt.Sprintf("mediaView(%d)", i)
	}
	return _mediaViewName[_mediaViewIndex[i]:_mediaViewIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _mediaViewNoOp() {
	var x [1]struct{}
	_ = x[mediaViewHome-(0)]
	_ = x[mediaViewURL-(1)]
	_ = x[mediaViewStorage-(2)]
	_ = x[mediaViewUpload-(3)]
}

var _mediaViewValues = []mediaView{mediaViewHome, mediaViewURL, mediaViewStorage, mediaViewUpload}

var _mediaViewNameToValueMap = map[string]mediaView{
	_mediaViewName[0:4]:        mediaViewHome,
	_mediaViewLowerName[0:4]:   mediaViewHome,
	_mediaViewName[4:7]:        mediaViewURL,
	_mediaViewLowerName[4:7]:   mediaViewURL,
	_mediaViewName[7:14]:       mediaViewStorage,
	_mediaViewLowerName[7:14]:  mediaViewStorage,
	_mediaViewName[14:20]:      mediaViewUpload,
	_mediaViewLowerName[14:20]: mediaViewUpload,
}

var _mediaViewNames = []string{
	_mediaViewName[0:4],
	_mediaViewName[4:7],
	_mediaViewName[7:14],
	_mediaViewName[14:20],
}

// mediaViewString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func mediaViewString(s string) (mediaView, error) {
	if val, ok := _mediaViewNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _mediaViewNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to mediaView values", s)
}

// mediaViewValues returns all values of the enum
func mediaViewValues() []mediaView {
	return _mediaViewValues
}

// mediaViewStrings returns a slice of all String values of the enum
func mediaViewStrings() []string {
	strs := make([]string, len(_mediaViewNames))
	copy(strs, _mediaViewNames)
	return strs
}

// IsAmediaView returns "true" if the value is listed in the enum definition. "false" otherwise
func (i mediaView) IsAmediaView() bool {
	for _, v := range _mediaViewValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for mediaView
func (i mediaView) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for mediaView
func (i *mediaView) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("mediaView should be a string, got %s", data)
	}

	var err error
	*i, err = mediaViewString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for mediaView
func (i mediaView) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for mediaView
func (i *mediaView) UnmarshalText(text []byte) error {
	var err error
	*i, err = mediaViewString(string(text))
	return err
}
