// Code generated by "enumer -type=iconKind,settingsSection -linecomment -json -text -output chrome_enums.go"; DO NOT EDIT.

package app

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _iconKindName = "reconnectmousepastemediastatsterminalminuspluspowersettingsfullscreenclose"

var _iconKindIndex = [...]uint8{0, 9, 14, 19, 24, 29, 37, 42, 46, 51, 59, 69, 74}

const _iconKindLowerName = "reconnectmousepastemediastatsterminalminuspluspowersettingsfullscreenclose"

func (i iconKind) String() string {
	if i >= iconKind(len(_iconKindIndex)-1) {
		return fmt.Sprintf("iconKind(%d)", i)
	}
	return _iconKindName[_iconKindIndex[i]:_iconKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _iconKindNoOp() {
	var x [64]struct{}
	_ = x[iconReconnect-(0)]
	_ = x[iconMouse-(1)]
	_ = x[iconPaste-(2)]
	_ = x[iconMedia-(3)]
	_ = x[iconStats-(4)]
	_ = x[iconTerminal-(5)]
	_ = x[iconMinus-(6)]
	_ = x[iconPlus-(7)]
	_ = x[iconPower-(8)]
	_ = x[iconSettings-(9)]
	_ = x[iconFullscreen-(10)]
	_ = x[iconClose-(11)]
}

var _iconKindValues = []iconKind{iconReconnect, iconMouse, iconPaste, iconMedia, iconStats, iconTerminal, iconMinus, iconPlus, iconPower, iconSettings, iconFullscreen, iconClose}

var _iconKindNameToValueMap = map[string]iconKind{
	_iconKindName[0:9]:        iconReconnect,
	_iconKindLowerName[0:9]:   iconReconnect,
	_iconKindName[9:14]:       iconMouse,
	_iconKindLowerName[9:14]:  iconMouse,
	_iconKindName[14:19]:      iconPaste,
	_iconKindLowerName[14:19]: iconPaste,
	_iconKindName[19:24]:      iconMedia,
	_iconKindLowerName[19:24]: iconMedia,
	_iconKindName[24:29]:      iconStats,
	_iconKindLowerName[24:29]: iconStats,
	_iconKindName[29:37]:      iconTerminal,
	_iconKindLowerName[29:37]: iconTerminal,
	_iconKindName[37:42]:      iconMinus,
	_iconKindLowerName[37:42]: iconMinus,
	_iconKindName[42:46]:      iconPlus,
	_iconKindLowerName[42:46]: iconPlus,
	_iconKindName[46:51]:      iconPower,
	_iconKindLowerName[46:51]: iconPower,
	_iconKindName[51:59]:      iconSettings,
	_iconKindLowerName[51:59]: iconSettings,
	_iconKindName[59:69]:      iconFullscreen,
	_iconKindLowerName[59:69]: iconFullscreen,
	_iconKindName[69:74]:      iconClose,
	_iconKindLowerName[69:74]: iconClose,
}

var _iconKindNames = []string{
	_iconKindName[0:9],
	_iconKindName[9:14],
	_iconKindName[14:19],
	_iconKindName[19:24],
	_iconKindName[24:29],
	_iconKindName[29:37],
	_iconKindName[37:42],
	_iconKindName[42:46],
	_iconKindName[46:51],
	_iconKindName[51:59],
	_iconKindName[59:69],
	_iconKindName[69:74],
}

// iconKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func iconKindString(s string) (iconKind, error) {
	if val, ok := _iconKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _iconKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to iconKind values", s)
}

// iconKindValues returns all values of the enum
func iconKindValues() []iconKind {
	return _iconKindValues
}

// iconKindStrings returns a slice of all String values of the enum
func iconKindStrings() []string {
	strs := make([]string, len(_iconKindNames))
	copy(strs, _iconKindNames)
	return strs
}

// IsAiconKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i iconKind) IsAiconKind() bool {
	for _, v := range _iconKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for iconKind
func (i iconKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for iconKind
func (i *iconKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("iconKind should be a string, got %s", data)
	}

	var err error
	*i, err = iconKindString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for iconKind
func (i iconKind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for iconKind
func (i *iconKind) UnmarshalText(text []byte) error {
	var err error
	*i, err = iconKindString(string(text))
	return err
}

const _settingsSectionName = "generalmousekeyboardvideohardwareatxaccessappearancemacrosnetworkmqttadvanced"

var _settingsSectionIndex = [...]uint8{0, 7, 12, 20, 25, 33, 36, 42, 52, 58, 65, 69, 77}

const _settingsSectionLowerName = "generalmousekeyboardvideohardwareatxaccessappearancemacrosnetworkmqttadvanced"

func (i settingsSection) String() string {
	if i >= settingsSection(len(_settingsSectionIndex)-1) {
		return fmt.Sprintf("settingsSection(%d)", i)
	}
	return _settingsSectionName[_settingsSectionIndex[i]:_settingsSectionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _settingsSectionNoOp() {
	var x [64]struct{}
	_ = x[sectionGeneral-(0)]
	_ = x[sectionMouse-(1)]
	_ = x[sectionKeyboard-(2)]
	_ = x[sectionVideo-(3)]
	_ = x[sectionHardware-(4)]
	_ = x[sectionATX-(5)]
	_ = x[sectionAccess-(6)]
	_ = x[sectionAppearance-(7)]
	_ = x[sectionMacros-(8)]
	_ = x[sectionNetwork-(9)]
	_ = x[sectionMQTT-(10)]
	_ = x[sectionAdvanced-(11)]
}

var _settingsSectionValues = []settingsSection{sectionGeneral, sectionMouse, sectionKeyboard, sectionVideo, sectionHardware, sectionATX, sectionAccess, sectionAppearance, sectionMacros, sectionNetwork, sectionMQTT, sectionAdvanced}

var _settingsSectionNameToValueMap = map[string]settingsSection{
	_settingsSectionName[0:7]:        sectionGeneral,
	_settingsSectionLowerName[0:7]:   sectionGeneral,
	_settingsSectionName[7:12]:       sectionMouse,
	_settingsSectionLowerName[7:12]:  sectionMouse,
	_settingsSectionName[12:20]:      sectionKeyboard,
	_settingsSectionLowerName[12:20]: sectionKeyboard,
	_settingsSectionName[20:25]:      sectionVideo,
	_settingsSectionLowerName[20:25]: sectionVideo,
	_settingsSectionName[25:33]:      sectionHardware,
	_settingsSectionLowerName[25:33]: sectionHardware,
	_settingsSectionName[33:36]:      sectionATX,
	_settingsSectionLowerName[33:36]: sectionATX,
	_settingsSectionName[36:42]:      sectionAccess,
	_settingsSectionLowerName[36:42]: sectionAccess,
	_settingsSectionName[42:52]:      sectionAppearance,
	_settingsSectionLowerName[42:52]: sectionAppearance,
	_settingsSectionName[52:58]:      sectionMacros,
	_settingsSectionLowerName[52:58]: sectionMacros,
	_settingsSectionName[58:65]:      sectionNetwork,
	_settingsSectionLowerName[58:65]: sectionNetwork,
	_settingsSectionName[65:69]:      sectionMQTT,
	_settingsSectionLowerName[65:69]: sectionMQTT,
	_settingsSectionName[69:77]:      sectionAdvanced,
	_settingsSectionLowerName[69:77]: sectionAdvanced,
}

var _settingsSectionNames = []string{
	_settingsSectionName[0:7],
	_settingsSectionName[7:12],
	_settingsSectionName[12:20],
	_settingsSectionName[20:25],
	_settingsSectionName[25:33],
	_settingsSectionName[33:36],
	_settingsSectionName[36:42],
	_settingsSectionName[42:52],
	_settingsSectionName[52:58],
	_settingsSectionName[58:65],
	_settingsSectionName[65:69],
	_settingsSectionName[69:77],
}

// settingsSectionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func settingsSectionString(s string) (settingsSection, error) {
	if val, ok := _settingsSectionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _settingsSectionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to settingsSection values", s)
}

// settingsSectionValues returns all values of the enum
func settingsSectionValues() []settingsSection {
	return _settingsSectionValues
}

// settingsSectionStrings returns a slice of all String values of the enum
func settingsSectionStrings() []string {
	strs := make([]string, len(_settingsSectionNames))
	copy(strs, _settingsSectionNames)
	return strs
}

// IsAsettingsSection returns "true" if the value is listed in the enum definition. "false" otherwise
func (i settingsSection) IsAsettingsSection() bool {
	for _, v := range _settingsSectionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for settingsSection
func (i settingsSection) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for settingsSection
func (i *settingsSection) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("settingsSection should be a string, got %s", data)
	}

	var err error
	*i, err = settingsSectionString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for settingsSection
func (i settingsSection) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for settingsSection
func (i *settingsSection) UnmarshalText(text []byte) error {
	var err error
	*i, err = settingsSectionString(string(text))
	return err
}
